apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: ingress-nginx
  annotations:
    # إخبار الكلاستر إن NGINX هو المسؤول عن هذا الـ Ingress
    kubernetes.io/ingress.class: "nginx"
    # تحويل الـ HTTP لـ HTTPS (لو ركبتي شهادة مستقبلاً)
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # زيادة وقت الانتظار للعمليات الطويلة في ArgoCD و Nexus
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # 1️⃣ الأبلكيشن بتاعك (الـ Hello App)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-app-service # تأكدي إن ده نفس إسم الـ Service في الـ Helm
                port:
                  number: 80

          # 2️⃣ واجهة ArgoCD
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80

          # 3️⃣ واجهة Nexus (مثال لو ضفتيه)
          - path: /nexus
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 8081