apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  # ❌ شيلنا الـ Annotations من هنا لأن الـ NLB هيكون عند الـ NGINX بس
spec:
  # ✅ النوع لازم يكون ClusterIP (بيتغير من values.yaml)
  type: {{ .Values.service.type | default "ClusterIP" }} 
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 80
      protocol: TCP