apiVersion: v1
kind: Service
metadata:
  name: hello-app-service # اسم ثابت يطابق الـ Ingress
spec:
  type: ClusterIP 
  selector:
    app: hello-app # تأكدي أن هذا الـ Label موجود في الـ Deployment pods
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP