replicaCount: 1

# values.yaml
image:
  repository: 389068786981.dkr.ecr.us-east-1.amazonaws.com/manar-app 
  tag: latest
  pullPolicy: Always


service:
  type: ClusterIP  # ๐ ูุงุฒู ูููู ุฏุงุฎูู ุนุดุงู ุงูู NGINX ูู ุงููู ููููู
  port: 80

ingress:
  enabled: true
  className: nginx  # ๐ ูุงุฒู ูููู nginx ุนุดุงู ุงูุจูุงุจุฉ (NGINX) ุชููุทู
  annotations:
    # ูุด ูุญุชุงุฌูู annotations ุจุชุงุนุฉ AWS ููุง ูุฃููุง ููุฌูุฏุฉ ูู ุงูู Controller ููุณู
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: ""  # ูู ูุนูุฏููุด ุฏูููู ุญูููู ุณูุจูู ูุงุถู ูุงูู NLB ููุดุชุบู ุจุงูู DNS ุจุชุงุนู
      paths:
        - path: /
          pathType: Prefix