name: Helm Deploy ALB Controller to EKS

on:
  workflow_run:
    workflows: ["Terraform Pipeline"]
    types:
      - completed

env:
  HELM_NAMESPACE: kube-system
  SERVICE_ACCOUNT: aws-load-balancer-controller
  HELM_RELEASE: aws-load-balancer-controller

jobs:
  deploy-alb:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: my-eks-cluster         # ممكن تعدل على حسب env
      AWS_REGION: us-east-1
      HELM_NAMESPACE: ${{ env.HELM_NAMESPACE }}
      SERVICE_ACCOUNT: ${{ env.SERVICE_ACCOUNT }}
      HELM_RELEASE: ${{ env.HELM_RELEASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-
